name: Notify Discord on Commit or Merge

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@2.0.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "New commit or merge on the main branch!"
