name: Run Unit Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install Flask
          pip install unittest

      - name: Run tests
        run: |
          . venv/bin/activate
          python -m unittest discover -s . -p "test_*.py"
